package modelo.entidad;
// Generated 24-sep-2022 21:25:11 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombre;
     private String apellido;
     private String telefono;
     private String direccion;

    public Estudiante() {
    }

    public Estudiante(String nombre, String apellido, String telefono, String direccion) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


