package modelo.entidad;
// Generated 06-nov-2022 9:39:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombre;
     private Set<PersonaRecibe> personaRecibes = new HashSet<PersonaRecibe>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(int idDepartamento, String nombre, Set<PersonaRecibe> personaRecibes) {
       this.idDepartamento = idDepartamento;
       this.nombre = nombre;
       this.personaRecibes = personaRecibes;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<PersonaRecibe> getPersonaRecibes() {
        return this.personaRecibes;
    }
    
    public void setPersonaRecibes(Set<PersonaRecibe> personaRecibes) {
        this.personaRecibes = personaRecibes;
    }




}


